In [2]:
import torch
torch.manual_seed(2026)

In [3]:
a = torch.ones((3, 3))
b = torch.randint(0, 10, (3, 2)).float()
c = a @ b

print('a =')
print(a)
print('----------')
print('b =')
print(b)
print('----------')
print('c =')
print(c)    

a =
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
----------
b =
tensor([[5., 4.],
        [8., 6.],
        [1., 7.]])
----------
c =
tensor([[14., 17.],
        [14., 17.],
        [14., 17.]])


In [4]:
torch.tril(torch.ones(3, 3))

tensor([[1., 0., 0.],
        [1., 1., 0.],
        [1., 1., 1.]])

In [5]:
a = torch.tril(torch.ones(3, 3))
# b = torch.randint(0, 10, (3, 2)).float()
a = a / torch.sum(a, dim=1, keepdim=True) # normalize the rows to sum to 1      
c = a @ b

print('a =')
print(a)
print('----------')
print('b =')
print(b)
print('----------')
print('c =')
print(c)    

a =
tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]])
----------
b =
tensor([[5., 4.],
        [8., 6.],
        [1., 7.]])
----------
c =
tensor([[5.0000, 4.0000],
        [6.5000, 5.0000],
        [4.6667, 5.6667]])
